### ISSUE TITLE
Small clarifications

### ISSUE THREAD

**Issue by greduan** [Fuco1/nave-mode#1]
I am a seasoned Vim user, or so I'd like to believe, I am not a newbie though.

I just want to say, `yw` means "yank word". That means put whatever `w` means into some yank buffer. Essentially, yes, copy a word. You can control which yank buffer this is though.

And `cw` does mean "change word". Essentially it puts the word into the default yank buffer, deletes the word and then enters insert mode.

Just wanted to clarify that. If a Vim expert has something to say about my explanation go ahead. :)

Would love to see this done, and then some thing that adds a modal interface. FYI I find the Vim interface very useful, mainly because I don't need the mouse and stuff just makes sense.

If you can convince me that a modal interface is not needed, with nave, maybe I can have a change of heart... I dare ya. ;)

**Comment by greduan** [comment]
I do see this as very useful for plugins though, becuase it'll really make navigating easier.

**Comment by Fuco1** [comment]
I suspect that one would be able to just plug this on top of evil maps if wanted.  I primarily want to define some framework of how to define motions, "text objects" and operations/filters on those.  What people do with it, what bindings they use etc. is out of scope of this project.

I can see it being used with `god-mode` as well.

Thanks for the clarifications, I'll update the readme accordingly.

**Comment by greduan** [comment]
Short post on this http://blog.schauderbasis.de/sane-default-navigation/
