### ISSUE TITLE
How is this going?

### ISSUE THREAD

**Issue by greduan** [Fuco1/nave-mode#2]
Hey @Fuco1, not to rush you or anything, seriously.

Just curious how this is looking in your horizon? Chances of this being implemented soon(-ish)?

If not, is there anything Vim converts-in-progress like me can do to help you?

**Comment by Fuco1** [comment]
This is a vision for far future. I haven't even thought about the basic setup. Once that is done, adding support for various operations/blocks/objects would be fairly simple.

**Comment by greduan** [comment]
Oh OK. That answers my question. :)
