### ISSUE TITLE
Let's get started

### ISSUE THREAD

**Issue by greduan** [Fuco1/nave-mode#3]
So I've recently gotten more into Emacs, but after years of Vim having no Vim-like "vocabulary" so to speak, to edit text is getting a bit annoying.

I've little ELisp and Lisp experience in general but I do understand it's terms and I can read the code, for sure.

How about we get this started? Gotta start somewhere no? :)

**Comment by Fuco1** [comment]
Well.

What would be needed is some magic keymap thing where you keep reading input until you hit some combination that can be executed.  That is going to be the most difficult thing to design and code, the rest is simple.

I imagine it as having maps which can start a command chain, then maps which can extend the command chain and finally maps which exit and cause execution (those would typically be the objects, word, line etc).

But sometimes a command might want to read more than one object or more than one combinator...  So the keymap chains need to be generated on the fly somehow.

I think this can be pretty much copied from evil, only made independent of various nonsense...

Sadly, I don't have time at all to start a new project now.

**Comment by greduan** [comment]
I see. Well. I'll look into it I guess. :)

We could also instead of listening for keys we could just remap all the keys in the keyboard, of course that would be in a separate file and not by default.

By default the user would just have access to all of these functions which can work together.

In any case I'll look into it. :)

**Comment by greduan** [comment]
@Fuco1 I've actually started working towards this recently, freaking finally.

https://github.com/greduan/emacs-texto

I won't implement the whole thing and ideas that Vim's modal interface brings, instead I'll just be implementing operators and text-objects. With that I think one can come to a very nice trade-off between the Emacs style of editing and Vim's style of editing.

Right now it's just in the research and brainstorming phase, as I am an Elisp newbie. But feel free to grab the idea and implement it if you want and/or find the time.
